import { Activity, ChevronRight, Clock3, Droplets, Gauge, Radio, SlidersHorizontal } from 'lucide-react'
import type { Device, Measurement, EventRow } from '../types'
import { formatDate } from '../lib/format'
import { StatusBadge, WaterLevelVisual, WaterChart, MetricCard, ActivityRow, EmptyPanel } from '../components/Shared'

export function DashboardView({ device, devices, measurements, activities, mqttStatus, onOpenWater, onOpenGateway }: { device: Device | null; devices: Device[]; measurements: Measurement[]; activities: EventRow[]; mqttStatus: string; onOpenWater: () => void; onOpenGateway: () => void }) {
  const currentPct = device?.readingStale ? null : device?.waterLevelPct ?? null
  const chartData = [...measurements].reverse().filter((row) => row.readingValid && row.waterLevelPct !== null).map((row) => ({ time: new Date(row.measuredAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), level: Number(row.waterLevelPct) }))
  const lastValid = device?.measuredAt && !device.readingStale ? formatDate(device.measuredAt) : 'No recent valid measurement'
  return <>
    <section className="hero-grid">
      <article className="level-card"><div className="level-card-top"><div><span className="panel-kicker">CURRENT WATER LEVEL</span><div className="level-primary">{currentPct === null ? '--' : currentPct.toFixed(1)}<small>%</small></div></div><WaterLevelVisual percentage={currentPct} status={device?.waterLevelStatus ?? null} /></div><div className="level-card-bottom"><div><span>CONDITION</span><StatusBadge value={currentPct === null ? device?.readingStale ? 'STALE' : 'NO DATA' : device?.waterLevelStatus} /></div><div><span>RAW SENSOR</span><strong>{currentPct === null ? '--' : device?.rawSensorValue ?? '--'}</strong></div><div><span>LAST VALID UPDATE</span><strong className="level-timestamp">{lastValid}</strong></div></div><button className="inline-link" onClick={onOpenWater}>View water-level history <ChevronRight size={15} /></button></article>
      <article className="gateway-card"><div className="panel-heading"><div><span className="panel-kicker">PHYSICAL GATEWAY</span><h2>Gateway state</h2></div><span className="gateway-glyph"><SlidersHorizontal size={18} /></span></div><div className="gateway-status-large"><StatusBadge value={device?.deviceStatus === 'OFFLINE' ? 'OFFLINE' : device?.gatewayStatus} kind="gateway" /></div><div className="gateway-reading"><div><span>SERVO ANGLE</span><strong>{device?.servoAngle === null || device?.servoAngle === undefined ? '--' : `${device.servoAngle} deg`}</strong></div><div><span>CONTROL MODE</span><StatusBadge value={device?.controlMode ?? 'UNCONFIGURED'} kind="gateway" /></div></div><div className="gateway-device-line"><span className={`mini-dot ${device?.deviceStatus === 'ONLINE' ? 'online' : ''}`} />{device?.deviceStatus ?? 'DEVICE NOT REGISTERED'}<span> / </span>{mqttStatus === 'connected' ? 'MQTT ready' : device?.deviceStatus === 'ONLINE' ? 'HTTP poll online' : 'No device command link'}</div><button className="gateway-manage" onClick={onOpenGateway}>Manage gateway <ChevronRight size={15} /></button></article>
    </section>
    <section className="metric-grid compact-metrics"><MetricCard label="REGISTERED DEVICES" value={String(devices.length)} detail={devices.length ? `${devices.filter((entry) => entry.deviceStatus === 'ONLINE').length} currently online` : 'No devices registered'} icon={Radio} tone="blue" /><MetricCard label="MEASUREMENTS STORED" value={String(measurements.length)} detail="From PostgreSQL history" icon={Activity} tone="teal" /><MetricCard label="WATER STATUS" value={device?.waterLevelStatus ?? '--'} detail={device?.readingStale ? 'Reading is stale' : 'Based on saved thresholds'} icon={Droplets} tone="amber" /><MetricCard label="GATEWAY MODE" value={device?.controlMode ?? '--'} detail="Independent from water status" icon={Gauge} tone="green" /></section>
    <section className="content-grid live-content-grid"><article className="panel chart-panel"><div className="panel-heading"><div><span className="panel-kicker">DATABASE MEASUREMENTS</span><h2>Water level history</h2><p>Recorded measurements  /  percentage</p></div><button className="text-button" onClick={onOpenWater}>Full history <ChevronRight size={15} /></button></div>{chartData.length ? <WaterChart data={chartData} /> : <EmptyPanel title="No water-level history yet" detail="The chart will populate after a calibrated measurement is received and stored." icon={Activity} />}<div className="chart-footnote"><span><i className="legend-dot" />Stored water-level measurements</span><span className="live-data-note">PostgreSQL source</span></div></article><article className="panel alert-panel"><div className="panel-heading compact-heading"><div><span className="panel-kicker">SYSTEM EVENT LOG</span><h2>Recent activity</h2></div><span className={`connection-pill ${mqttStatus === 'connected' ? 'connected' : 'offline'}`}><i />{mqttStatus === 'connected' ? 'MQTT ONLINE' : 'MQTT OFFLINE'}</span></div>{activities.length ? <div className="activity-list">{activities.slice(0, 5).map((event) => <ActivityRow key={`${event.type}-${event.id}`} event={event} />)}</div> : <EmptyPanel title="No activity recorded" detail="Device and administrator events will appear here." icon={Clock3} compact />}<div className="activity-panel-foot"><span><span className="footer-dot" />Events are stored in PostgreSQL</span></div></article></section>
  </>
}
