import { Activity, ArrowDownRight, ArrowUpRight, Waves } from 'lucide-react'
import type { Device, Measurement } from '../types'
import { formatDate } from '../lib/format'
import { StatusBadge, WaterLevelVisual, WaterChart, MetricCard, EmptyPanel } from '../components/Shared'

export function WaterView({ device, measurements }: { device: Device | null; measurements: Measurement[] }) {
  const values = measurements.filter((item) => item.readingValid).map((item) => item.waterLevelPct).filter((value): value is number => value !== null)
  const stats = values.length ? { min: Math.min(...values), max: Math.max(...values), avg: values.reduce((sum, value) => sum + value, 0) / values.length } : null
  const data = [...measurements].reverse().filter((row) => row.readingValid && row.waterLevelPct !== null).map((row) => ({ time: formatDate(row.measuredAt), level: Number(row.waterLevelPct) }))
  const current = device?.readingStale ? null : device?.waterLevelPct ?? null
  return <><section className="water-detail-grid"><article className="panel water-current-panel"><div className="panel-heading"><div><span className="panel-kicker">LATEST STORED MEASUREMENT</span><h2>Water level</h2></div><StatusBadge value={current === null ? device?.readingStale ? 'STALE' : 'NO DATA' : device?.waterLevelStatus} /></div><div className="water-current-content"><WaterLevelVisual percentage={current} status={device?.waterLevelStatus ?? null} /><div className="water-current-numbers"><strong>{current === null ? '--' : `${current.toFixed(1)}%`}</strong><span>{device?.waterLevelM === null || device?.waterLevelM === undefined ? 'Physical unit not calibrated' : `${device.waterLevelM.toFixed(2)} m`}</span><div className="raw-reading"><span>RAW SENSOR READING</span><b>{device?.rawSensorValue ?? '--'}</b></div><div className="raw-reading"><span>MEASURED AT</span><b>{formatDate(device?.measuredAt)}</b></div></div></div></article><div className="water-stat-stack"><MetricCard label="MINIMUM RECORDED" value={stats ? `${stats.min.toFixed(1)}%` : '--'} detail="Selected history result" icon={ArrowDownRight} tone="blue" /><MetricCard label="MAXIMUM RECORDED" value={stats ? `${stats.max.toFixed(1)}%` : '--'} detail="Selected history result" icon={ArrowUpRight} tone="teal" /><MetricCard label="AVERAGE LEVEL" value={stats ? `${stats.avg.toFixed(1)}%` : '--'} detail={`${values.length} stored measurements`} icon={Activity} tone="amber" /></div></section><section className="panel water-history-panel"><div className="panel-heading"><div><span className="panel-kicker">POSTGRESQL RECORDS</span><h2>Water-level trend</h2><p>Only valid, stored sensor measurements are plotted.</p></div><span className="record-count">{values.length} records</span></div>{data.length ? <WaterChart data={data} /> : <EmptyPanel title="No measurements available" detail="Connect a calibrated IoT sensor and save its first reading to view a trend." icon={Waves} />}</section></>
}
